import './globals.css'

export const metadata = {
  title: 'FXDL Chat Bot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-800  min-h-screen'>{children}</body>
    </html>
  )
}
